### PR TITLE
Add a __main.py__ to allow running this like `cat`

### PR DESCRIPTION
**Pull request by jap**
Example usage:
```
$ black -S demoji/__main__.py 2>&1 | python3 -m demoji
All done! :sparkles: :shortcake: :sparkles:
1 file left unchanged.
```

### CODE REVIEW

**Comment by bsolomon1124** [comment]
Thanks @jap , I like this idea.

I've added `argparse` for `-h`/`--help`.

```sh
Examples:

    $ python3 -m demoji -h
    usage: __main__.py [-h] files [files ...]

    positional arguments:
      files       One or more Python files to demoji-fy, or '-' for stdin; also accepts piped stdin

    optional arguments:
      -h, --help  show this help message and exit

    $ python3 -m demoji -
    All done! ✨ 🍰 ✨
    All done! :sparkles: :shortcake: :sparkles:

    $ echo 'All done! ✨ 🍰 ✨' | python3 -m demoji
    All done! :sparkles: :shortcake: :sparkles:

    $ echo 'All done! ✨ 🍰 ✨' > out.txt && python3 -m demoji out.txt
    All done! :sparkles: :shortcake: :sparkles:
```

What do you think?

**Comment by bsolomon1124** [comment]
Added to test PyPI:

```
python3 -m pip install --index-url https://test.pypi.org/simple/ --pre demoji
```

**Comment by jap** [comment]
Looks good to me! Only other thing I was wondering about is adding an entrypoint so you can just invoke `demoji` instead of having to spell out `python3 -m demoji`

**Comment by bsolomon1124** [comment]
> Only other thing I was wondering about is adding an entrypoint so you can just invoke demoji 

Done.

**Pull request merged**
